#!/bin/bash
#
#  Copyright (c) 2025, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

# Apply git patch idempotently (no-op if already applied)
# Usage: apply_patch <patch_file>
apply_patch()
{
    local patch_file="$1"

    if [[ ! -f "${patch_file}" ]]; then
        echo "ERROR: Patch file not found: ${patch_file}" >&2
        return 1
    fi

    # Try to apply the patch
    if git apply "${patch_file}" 2>/dev/null; then
        return 0
    fi

    # Check if already applied
    if git apply --check "${patch_file}" 2>&1 | grep -q "already applied"; then
        return 0
    fi

    # Patch failed and wasn't already applied
    echo "ERROR: Failed to apply patch: ${patch_file}" >&2
    return 1
}

export OT_SRCDIR="$(pwd)"
export OUT_FOLDER="${OT_SRCDIR}/${OT_CMAKE_BUILD_DIR:-build}"
OT_CMAKE_NINJA_TARGET=${OT_CMAKE_NINJA_TARGET:-}

#to add more by modify ld
is_create_ld_gen()
{
    local ldgentargets=("rtl8777g" "rtl8777g_s" "evb" "evb_dual" \
    "rtl8777g_cert" "rtl8777g_test" "otbr" "rtl8777g_ncp")

    for ldgentarget in "${ldgentargets[@]}"; do
        if [ "${board_target}" == "${ldgentarget}" ]; then
            return 0
        fi
    done

    return 1
}

#modify folder to vendor/rtl8777g
is_rtl8777g_signal_target()
{
    local is8777gsignaltargets=("rtl8777g" "rtl8777g_cert")

    for is8777gsignaltarget in "${is8777gsignaltargets[@]}"; do
        if [ "${board_target}" == "${is8777gsignaltarget}" ]; then
            return 0
        fi
    done

    return 1
}

build()
{
    mkdir -p "${OUT_FOLDER}"
    cd "${OUT_FOLDER}"
    rm -rf "${OUT_FOLDER}/bin"

    cmake -GNinja -DOT_COMPILE_WARNING_AS_ERROR=ON "$@" "${OT_SRCDIR}"

    if [[ -n ${OT_CMAKE_NINJA_TARGET[*]} ]]; then
        ninja "${OT_CMAKE_NINJA_TARGET[@]}"
    else
        ninja
    fi
}

pre_build()
{
    # for rtl87x2g
    if is_create_ld_gen >/dev/null 2>&1; then
       ${OT_SRCDIR}/Realtek/pre_build ${BUILD_BANK} ${target} ${platform} "app.ld"
    fi
    # for rtl8752h
    if [ "${platform}" == "rtl8752h" ]; then
        if [ "${OT_CMAKE_NINJA_TARGET}" == "ot-rcp" ]; then
            ${OT_SRCDIR}/Realtek/pre_build "bank0" ${target} ${platform} "rcp.ld"
        else
            ${OT_SRCDIR}/Realtek/pre_build "bank0" ${target} ${platform} "app.ld"
        fi
    fi
}

post_build()
{
    # for rtl87x2g
    if is_create_ld_gen >/dev/null 2>&1; then
        ${OT_SRCDIR}/Realtek/post_build ${BUILD_BANK} ${OT_CMAKE_NINJA_TARGET} ${platform}
        rm -f ${OT_SRCDIR}/vendor/${platform}/${target}/*.gen
    fi
    # for rtl8752h
    if [ "${platform}" == "rtl8752h" ]; then
        ${OT_SRCDIR}/Realtek/post_build "bank0" ${OT_CMAKE_NINJA_TARGET} ${platform}
        rm -f ${OT_SRCDIR}/vendor/${platform}/${target}/*.gen
    fi
}

set_sdk_path()
{
   case "${platform}" in
        rtl87x2g)
            export REALTEK_SDK_PATH="${OT_SRCDIR}/../../"
            ;;
        rtl8752h)
            export REALTEK_SDK_PATH="${OT_SRCDIR}/../.."
            ;;
        *)
   esac
}


rtl87x2g_platform()
{
    options+=("-DRT_PLATFORM=${platform}")
    options+=("-DBUILD_BOARD_TARGET=${board_target}")
    options+=("-DBUILD_TARGET=${target}")
    case "${OT_CMAKE_NINJA_TARGET}" in
        ot-cli-ftd | ot-cli-mtd)
            cd ${OT_SRCDIR}/openthread && git reset --hard HEAD && git clean -f -d && git checkout thread-reference-20250612 && apply_patch ../openthread_csl.patch && cd ${OT_SRCDIR}
            options+=("-DCMAKE_TOOLCHAIN_FILE=vendor/${platform}/arm-none-eabi.cmake")
            options+=("-DENABLE_CLI=ON")
            ;;
        ot-ncp-ftd | ot-ncp-mtd)
            # update to latest openthread commits
            options+=("-DCMAKE_TOOLCHAIN_FILE=vendor/${platform}/arm-none-eabi.cmake")
            options+=("-DENABLE_CLI=ON")
            ;;
        ot-rcp)
			cd ${OT_SRCDIR}/openthread && git reset --hard HEAD && git clean -f -d && git checkout thread-reference-20250612 && cd ${OT_SRCDIR}
            options+=("-DCMAKE_TOOLCHAIN_FILE=vendor/${platform}/arm-none-eabi.cmake")
            options+=("-DENABLE_CLI=OFF -DOT_DNSSD_SERVER=ON -DOT_SRP_SERVER=ON")
            options+=("-DOT_NCP_VENDOR_HOOK_SOURCE=$PWD/vendor/${platform}/example_vendor_hook.cpp")
            ;;
        *)
            ;;
    esac
    options+=("-DOT_CMAKE_NINJA_TARGET=${OT_CMAKE_NINJA_TARGET}")
}

rtl8752h_platform()
{
    options+=("-DCMAKE_TOOLCHAIN_FILE=vendor/${platform}/arm-none-eabi.cmake")
    options+=("-DRT_PLATFORM=${platform}")
    #options+=("-DBUILD_BOARD_TARGET=${board_target}")
    options+=("-DBUILD_TARGET=${target}")
    options+=("-DRT_PATCH=ON")
    case "${OT_CMAKE_NINJA_TARGET}" in
        ot-cli-mtd)
            cd ${OT_SRCDIR}/openthread && git reset --hard HEAD && git clean -f -d && git checkout thread-reference-20250612 && apply_patch ../openthread_csl.patch && cd ${OT_SRCDIR}
            ;;
        ot-rcp)
            case "${board_target}" in
                rtl8771htv)
                    options+=("-DOT_NCP_VENDOR_HOOK_SOURCE=$PWD/vendor/${platform}/example_vendor_hook.cpp")
                    cd ${OT_SRCDIR}/openthread && git reset --hard HEAD && git clean -f -d && git checkout thread-reference-20250612 && cd ${OT_SRCDIR}
                    ;;
                *)
                    cd ${OT_SRCDIR}/openthread && git checkout 2aeb8b8 && cd ${OT_SRCDIR}
                    ;;
            esac
            options+=("-DOT_DNSSD_SERVER=ON -DOT_SRP_SERVER=ON")
            #case "${build_type}" in
            #    dev)
            #        tar zxvf ${OT_SRCDIR}/Realtek/v3.0.0.tar.gz -C ${OT_SRCDIR}/openthread/third_party/mbedtls/
            #        ;;
            #esac
            ;;
        *)
            ;;
    esac
    options+=("-DOT_CMAKE_NINJA_TARGET=${OT_CMAKE_NINJA_TARGET}")
}

main()
{
    local platform="$1"
    local build_type="$2"
    local board_target="$3"
    local target="$3"
    local options

    if is_rtl8777g_signal_target; then
        target="rtl8777g"
    fi

    if is_create_ld_gen >/dev/null 2>&1; then
        BUILD_BANK="bank0"
    fi

    set_sdk_path

    options+=("-DBUILD_TYPE=${build_type}")
    options+=("-DCMAKE_BUILD_TYPE=Release")
    case "${platform}" in
        rtl87x2g)
            rtl87x2g_platform;;
        rtl8752h)
            rtl8752h_platform;;
    esac

    options+=("$@")

    pre_build
    build "${options[@]}"
    post_build

    #if [ "${OT_CMAKE_NINJA_TARGET}" == "ot-rcp" ] && [ ${board_target} == "rtl8752h" ];then
    #    grep "__librtl8752h_internal_length" ${OT_SRCDIR}/build/ot-rcp.map
    #    grep "__librtl8752h_peripheral_length" ${OT_SRCDIR}/build/ot-rcp.map
    #    grep "__libopenthread_rtl8752h_length" ${OT_SRCDIR}/build/ot-rcp.map
    #    grep "__libopenthread_radio_length" ${OT_SRCDIR}/build/ot-rcp.map
    #    grep "__libopenthread_rcp_length" ${OT_SRCDIR}/build/ot-rcp.map
    #    grep "__libopenthread_spinel_rcp_length" ${OT_SRCDIR}/build/ot-rcp.map
    #    grep "__libopenthread_hdlc_length" ${OT_SRCDIR}/build/ot-rcp.map
    #    grep "__rw_length" ${OT_SRCDIR}/build/ot-rcp.map
    #    grep "__bss_length__" ${OT_SRCDIR}/build/ot-rcp.map
    #fi
}

main "$@"
