
# OpenThread config

if(${OT_CMAKE_NINJA_TARGET} STREQUAL "matter-cli-ftd" OR ${OT_CMAKE_NINJA_TARGET} STREQUAL "matter-cli-mtd")
    # config for matter have been moved to matter repository
else()

if(${RT_PLATFORM} STREQUAL "rtl87x2g")
    set(OT_PLATFORM "external" CACHE STRING "")
    set(OT_SLAAC ON CACHE BOOL "")
    set(OT_BORDER_AGENT ON CACHE BOOL "")
    set(OT_BORDER_ROUTER ON CACHE BOOL "")
    set(OT_COMMISSIONER ON CACHE BOOL "")
    set(OT_JOINER ON CACHE BOOL "")
    set(OT_DNS_CLIENT ON CACHE BOOL "")
    set(OT_DHCP6_SERVER ON CACHE BOOL "")
    set(OT_DHCP6_CLIENT ON CACHE BOOL "")
    set(OT_COAP ON CACHE BOOL "")
    set(OT_COAPS ON CACHE BOOL "")
    set(OT_COAP_OBSERVE ON CACHE BOOL "")
    set(OT_LINK_RAW ON CACHE BOOL "")
    set(OT_MAC_FILTER ON CACHE BOOL "")
    set(OT_SERVICE ON CACHE BOOL "")

    set(OT_ECDSA ON CACHE BOOL "")
    set(OT_SNTP_CLIENT ON CACHE BOOL "")
    set(OT_CHILD_SUPERVISION ON CACHE BOOL "")
    set(OT_JAM_DETECTION ON CACHE BOOL "")
    set(OT_LOG_LEVEL_DYNAMIC ON CACHE BOOL "")
    set(OT_EXTERNAL_HEAP ON CACHE BOOL "")
    set(OT_SRP_CLIENT ON CACHE BOOL "")
    set(OT_DUA ON CACHE BOOL "")
    set(OT_BACKBONE_ROUTER ON CACHE BOOL "")
    set(OT_MLR ON CACHE BOOL "")
    set(OT_CSL_RECEIVER ON CACHE BOOL "")
    set(OT_LINK_METRICS_INITIATOR ON CACHE BOOL "")
    set(OT_LINK_METRICS_SUBJECT ON CACHE BOOL "")
    set(OT_CHANNEL_MONITOR OFF CACHE BOOL "")
    
if(${BUILD_TARGET} STREQUAL "otbr")
    set(OT_BORDER_ROUTING ON CACHE BOOL "")
    set(OT_TMF_ANYCAST_LOCATOR ON CACHE BOOL "")
    set(OT_BORDER_AGENT_ID ON CACHE BOOL "")
    set(OT_BORDER_ROUTING_DHCP6_PD OFF CACHE BOOL "")
    set(OT_IP6_BR_COUNTERS ON CACHE BOOL "")
    set(OT_DATASET_UPDATER ON CACHE BOOL "")
    set(OT_DNS_UPSTREAM_QUERY ON CACHE BOOL "")
    set(OT_DNSSD_SERVER ON CACHE BOOL "")
    set(OT_NAT64_BORDER_ROUTING ON CACHE BOOL "")
    set(OT_NAT64_TRANSLATOR ON CACHE BOOL "")
    set(OT_NETDATA_PUBLISHER ON CACHE BOOL "")
    set(OT_TMF_NETDIAG_CLIENT ON CACHE BOOL "")
    set(OT_PLATFORM_NETIF ON CACHE BOOL "")
    set(OT_PLATFORM_UDP ON CACHE BOOL "")
    set(OT_SRP_SERVER ON CACHE BOOL "")
    set(OT_UPTIME ON CACHE BOOL "")
    set(OT_MLE_STEERING_DATA_SET_OOB ON CACHE BOOL "")
    set(OT_TMF_PROXY_DUA ON CACHE BOOL "")
    set(OT_TMF_PROXY_MLR ON CACHE BOOL "")
    set(OT_UDP_FORWARD OFF CACHE BOOL "")
    
    set(OT_TCP OFF CACHE BOOL "")
else()
    set(OT_CHANNEL_MANAGER OFF CACHE BOOL "")
    set(OT_UDP_FORWARD ON CACHE BOOL "")
    message("OT_CHANNEL_MANAGER not set")
endif()

    if(${OT_CMAKE_NINJA_TARGET} STREQUAL "ot-cli-ftd" 
    OR ${OT_CMAKE_NINJA_TARGET} STREQUAL "ot-cli-mtd"
    OR ${OT_CMAKE_NINJA_TARGET} STREQUAL "ot-rcp"
    OR ${OT_CMAKE_NINJA_TARGET} STREQUAL "ot-ncp-ftd")
        set(OT_EXTERNAL_MBEDTLS "mbedtls" CACHE STRING "")
    endif()
endif()

if(${RT_PLATFORM} STREQUAL "rtl8752h")
if(${OT_CMAKE_NINJA_TARGET} STREQUAL "ot-cli-mtd")
    set(OT_PLATFORM "external" CACHE STRING "")
    set(OT_SLAAC ON CACHE BOOL "")
    set(OT_LOG_LEVEL_DYNAMIC ON CACHE BOOL "")
    set(OT_EXTERNAL_HEAP ON CACHE BOOL "")
    set(OT_CSL_RECEIVER ON CACHE BOOL "")
    set(OT_LINK_METRICS_INITIATOR ON CACHE BOOL "")
    set(OT_LINK_METRICS_SUBJECT ON CACHE BOOL "")
endif()
if(${OT_CMAKE_NINJA_TARGET} STREQUAL "ot-rcp")
    set(OT_PLATFORM "external" CACHE STRING "")
    set(OT_SLAAC ON CACHE BOOL "")
    set(OT_BORDER_AGENT ON CACHE BOOL "")
    set(OT_BORDER_ROUTER ON CACHE BOOL "")
    set(OT_COMMISSIONER ON CACHE BOOL "")
    set(OT_JOINER ON CACHE BOOL "")
    set(OT_DNS_CLIENT ON CACHE BOOL "")
    set(OT_DHCP6_SERVER ON CACHE BOOL "")
    set(OT_DHCP6_CLIENT ON CACHE BOOL "")
    set(OT_COAP ON CACHE BOOL "")
    set(OT_COAPS ON CACHE BOOL "")
    set(OT_COAP_OBSERVE ON CACHE BOOL "")
    set(OT_LINK_RAW ON CACHE BOOL "")
    set(OT_MAC_FILTER ON CACHE BOOL "")
    set(OT_SERVICE ON CACHE BOOL "")
    set(OT_UDP_FORWARD ON CACHE BOOL "")
    set(OT_ECDSA ON CACHE BOOL "")
    set(OT_SNTP_CLIENT ON CACHE BOOL "")
    set(OT_CHILD_SUPERVISION ON CACHE BOOL "")
    set(OT_JAM_DETECTION ON CACHE BOOL "")
    set(OT_LOG_LEVEL_DYNAMIC ON CACHE BOOL "")
    set(OT_EXTERNAL_HEAP ON CACHE BOOL "")
    set(OT_SRP_CLIENT ON CACHE BOOL "")
    set(OT_DUA ON CACHE BOOL "")
    set(OT_BACKBONE_ROUTER ON CACHE BOOL "")
    set(OT_MLR ON CACHE BOOL "")
    set(OT_CSL_RECEIVER ON CACHE BOOL "")
    set(OT_LINK_METRICS_INITIATOR ON CACHE BOOL "")
    set(OT_LINK_METRICS_SUBJECT ON CACHE BOOL "")
    set(OT_CHANNEL_MONITOR OFF CACHE BOOL "")
    set(OT_CHANNEL_MANAGER OFF CACHE BOOL "")
endif()
endif()

endif()


set(OT_PLATFORM_LIB "openthread-${RT_PLATFORM}")

add_subdirectory(${OT_REALTEK_ROOT}/openthread ${CMAKE_CURRENT_BINARY_DIR}/openthread)

target_compile_definitions(ot-config INTERFACE
    OPENTHREAD_CONFIG_FILE="openthread-core-${RT_PLATFORM}-config.h"
    OPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE="openthread-core-${RT_PLATFORM}-config-check.h"
)

if(${OT_CMAKE_NINJA_TARGET} STREQUAL "ot-rcp")
    target_compile_definitions(ot-config INTERFACE
        OPENTHREAD_PROJECT_CORE_CONFIG_FILE="openthread-core-${BUILD_TARGET}-rcp-config.h"
    )
else()
    target_compile_definitions(ot-config INTERFACE
        OPENTHREAD_PROJECT_CORE_CONFIG_FILE="openthread-core-${RT_PLATFORM}-config.h"
    )
endif()

target_include_directories(ot-config INTERFACE
    ${OT_REALTEK_ROOT}/openthread/examples/platforms
    ${OT_REALTEK_ROOT}/src/${RT_PLATFORM}
    ${REALTEK_SDK_INCPATH}
)
